# Generated by Django 4.1.7 on 2023-12-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UmbrellaApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitestorage",
            name="site_id",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="UmbrellaApp.site",
                verbose_name="站点ID",
            ),
        ),
    ]
