# Generated by Django 4.1.7 on 2023-12-07 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UmbrellaApp", "0006_umbrella_umbrella_scrapped"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="umbrella_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="UmbrellaApp.umbrella",
                verbose_name="雨伞ID",
            ),
        ),
        migrations.AlterField(
            model_name="diary",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户ID",
            ),
        ),
    ]
