# Generated by Django 4.1.7 on 2023-12-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UmbrellaApp", "0007_alter_diary_umbrella_id_alter_diary_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="评价时间"),
        ),
    ]
