# Generated by Django 4.1.7 on 2023-12-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UmbrellaApp", "0008_comment_comment_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="umbrella", name="umbrella_available",),
    ]
