# Generated by Django 4.1.7 on 2023-12-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UmbrellaApp", "0009_remove_umbrella_umbrella_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="coupon_type",
            field=models.BooleanField(verbose_name="优惠券类型"),
        ),
    ]
