# Generated by Django 4.1.7 on 2023-12-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UmbrellaApp", "0010_alter_coupon_coupon_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="available",
            field=models.BooleanField(default=True, verbose_name="是否可用"),
        ),
    ]
